### ISSUE TITLE
Documentation code block missing import

### ISSUE THREAD

**Issue by Giatroo** [bigdatabr/deirokay#54]
The following code block explains about how to validate data:

https://github.com/bigdatabr/deirokay/blob/546e5d1c599decb9d5694d5c10c3154d29c109dc/docs/source/getting_started.rst?plain=1#L216

However, the method `validate` is being used and it not being imported. 
It's the first time the reader meets this method, and it's not clear to them where it comes from.

**Comment by bressanmarcos** [comment]
Solved, thank's for your issue :)
